### ISSUE TITLE
Undefined array key "token" in checkout

### ISSUE THREAD

**Issue by orkuncv** [dpdconnect/magento2-shipping#61]
DPD module does not work on my local environment. 

``
Exception #0 (Exception): Warning: Undefined array key "token" in 
vendor/dpdconnect/php-sdk/src/Common/AuthenticatedHttpClient.php on line 77
``

**To Reproduce**
1. Add product to cart
2. Go to checkout

**Actual result**
Warning: Undefined array key "token" 

**Information**
- Magento version: 2.4.4-p2
- PHP version: 8.1
- DPD module version: 1.2.6

**Comment by dpdplugin** [comment]
Hi @orkuncv 
This means you don't have proper DPD credentials or they are not properly configured at DPD's side.
Could you contact us at support@x-interactive.nl with your username?

**Comment by Davie82** [comment]
Hi @dpdplugin,

I am also running into this problem.

When working in our local environment, we want to prevent data from going to any production environment. This also includes third parties. Adding DPD credentials is therefore not the right solution.

Other modules actually always have an option to disable the functionality. Or the modules contain some logic to skip everything if the token is not provided. Another solution is to log an error instead of displaying it, because now it it not possible to get into the checkout.

**Comment by orkuncv** [comment]
Can this ticket be reopened?
This issue is still not resolved in version 1.2.9

The same API credentials works on the production and staging environment, but on the local environment it does not.

**Comment by dpdplugin** [comment]
@orkuncv 
The module tries to get a token from DPD, which the webservice returns on valid and properly configured credentials.
In your case something is not right, which can be the credentials or something on your local environment what makes the module not able to connect to DPD.

**Comment by hostep** [comment]
Also running into this error.
This happens when the module isn't configured yet for example.

@dpdplugin: would be great if the module doesn't crash the checkout when it's not configured properly yet, it should just handle this gracefully without crashing.

**Comment by hostep** [comment]
This error still happens after having received the correct credentials from our client and using them (in my local environment). After some debugging, the underlying error message that causes the problem is `{"code":401,"message":"JWT Token not found"}`

I've also noticed that not only the checkout crashes, but also in the backoffice when you go to Shipping Methods, which is also highly annoying.

We'll keep this module disabled for now, as it's quite annoying, until we've found a way to fix this with our client and DPD support, or if that doesn't work out, we'll advise our client to move to a different shipping provider.
